[WIP] Feature/export json-pdf
ZupIT/horusec-platform pull request #80
Opened 2021-05-31 13:59 UTC by lucasgarciazup

**- What I did**

**- How to verify it**

**- Description for the changelog**

2021-06-03 13:28 UTC, lucasbrunozup requested changes
Eu também tive que alterar as ordens do graficos no PR #82 , será que não vai bugar os export não ?

2021-06-03 13:28 UTC, lucasbrunozup commented on manager/src/helpers/formatters/xlsx.ts
> +  const ws_data = [
Opte por usar pascalCase ao invés de snake_case, para mantermos o padrão do projeto.

2021-06-03 13:28 UTC, lucasbrunozup commented on manager/src/helpers/formatters/xlsx.ts
> +export function createReportWS(data: DashboardData) {
O que significa WS ?

2021-06-03 13:28 UTC, lucasbrunozup commented on manager/src/helpers/formatters/xlsx.ts
> +    data.vulnerabilitiesByRepository.forEach((el) => {
Talvez, se usar "vul" ou "vuln" ao invés de "el" fica mais explicito o que ele significa.

2021-06-03 13:28 UTC, lucasbrunozup commented on manager/src/pages/Internal/Dashboard/TotalRepositories/index.tsx
> +    <div className="block half-space" id="total-repositories">
Removi essa div no meu PR #82 pode dar conflitos

2021-06-03 13:28 UTC, lucasbrunozup commented on manager/src/helpers/formatters/xlsx.ts
> +  instance: (string | number)[][]
Essa instance é da Row ?  Talvez instanceRow fique mais objetivo.

2021-06-07 12:35 UTC, lucasgarciazup commented on manager/src/helpers/formatters/xlsx.ts
> +export function createReportWS(data: DashboardData) {
workSheet,

2021-06-07 19:29 UTC, lucasbrunozup approved these changes

2021-06-07 19:29 UTC, merged